# Generated by Django 2.0.2 on 2018-02-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music1', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favourite',
        ),
    ]
